version: "2.0"
services:
    #PHP Service
    laravel:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel
        user: "1000:1000"
        container_name: laravel
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: laravel
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - app-network

    #Mysql DB
    mysql:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vita_meals
        volumes:
            - ../mysql:/mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    mysql:
        driver: local
