version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
        depends_on:
            - database

    database:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vita_meals
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app

volumes:
    mysql-data:
